apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: namespace-workflow-1732953331668
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080